export enum EnvKeys {
  BACKEND_PORT = 'BACKEND_PORT',
  BACKEND_JWT_SECRET_KEY = 'BACKEND_JWT_SECRET_KEY',
  BACKEND_JWT_EXPIRATION_TIME = 'BACKEND_JWT_EXPIRATION_TIME',
  BACKEND_DB_HOST = 'BACKEND_DB_HOST',
  BACKEND_DB_PORT = 'BACKEND_DB_PORT',
  BACKEND_DB_USERNAME = 'BACKEND_DB_USERNAME',
  BACKEND_DB_PASSWORD = 'BACKEND_DB_PASSWORD',
  BACKEND_DB_DATABASE = 'BACKEND_DB_DATABASE',
}
